### ISSUE TITLE
Variants doubled with a subset bed file for the same vcf file

### ISSUE THREAD

**Issue by justwalking2017** [verilylifesciences/genomewarp#4] opened 2018-01-04 18:57 UTC
Dear all,
I use the same vcf file from hg37 run two times with a bed and its subset.
However, I get double variants with the subset bed, the number of which even more reasonable for normal sense.
Could you help me figure out what happened behind this result

#####brief points for two run####
INPUT1: VCF1, BED1, Hg37.fa, hg19to38.chain.file, hg38
OUTPUT1: VCF1_output1, BED1_output;

INPUT2: VCF1, BED2, Hg37.fa, hg19to38.chain.file, hg38
OUTPUT2: VCF1_output2, BED2_output

Initial variants in VCF1: 4875314
Initial bases in BED1: 2806545357
Initial bases in BED2: 2728614045
**Relationship between BED1 and BED2: BED2 is a totally subset of BED1**
Variants in VCF1_output1: **2102101**
Variants in VCF1_output2: **3983104**
bases in BED1_output: 1143768646
bases in BED2_output: 2628402283
 
#######file used for two run##############
VCF1: ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/NISTv3.3.2/GRCh37/supplementaryFiles/inputvcfsandbeds/HG001_GRCh37_CHROM1-MT_novoalign_Ilmn150bp300X_FB.vcf.gz

BED1: ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/NISTv3.3.2/GRCh37/supplementaryFiles/inputvcfsandbeds/HG001_GRCh37_CHROM1-MT_novoalign_Ilmn150bp300X_callableloci.bed
note: keep "callable" position only according the lable information in column 4

BEDg: ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/NISTv3.3.2/GRCh37/supplementaryFiles/inputvcfsandbeds/HG001_GRCh37_CHROM1-X_novoalign_Ilmn150bp300X_GATKHC_gvcf_callable.bed
BED2: Intersect region of BED1 and BEDg by "bedtools-intersect" command

hg37.fa: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz
hg38,fa: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna.gz
chainfile:
http://hgdownload.cse.ucsc.edu/goldenpath/hg19/liftOver/hg19ToHg38.over.chain.gz

Thanks for your time

**Comment by cmclean** [comment] 2018-01-04 21:21
Hi @justwalking2017,

Thanks for your comment. The likely reason you see this behavior, where having a subset of the genome result in a larger fraction of the genome successfully converted, is mentioned briefly in the Notes section of the Readme: "GenomeWarp is deliberately conservative in tricky cases, preferring to omit a confidently-called region and its constituent variants if there is not an unambiguous mapping."

Concretely, there is a filtering step at https://github.com/verilylifesciences/genomewarp/blob/master/src/main/java/com/verily/genomewarp/TransformVariantsInRange.java#L118-L138 for tricky cases that are not addressed. One major unaddressed case is when the BED region that was mapped across assemblies contains one or more insertion/deletion changes. Those assembly-based indels would induce changes in the VCF output in an assembly-dependent manner and that has not been implemented in this version of the code.

My hypothesis that this is the cause of what you see could be checked by passing in the --intermediate_files flag to your run of the code and then inspecting the resultant 'out.bed.annotated' file in your output directory -- the final column in that file indicates the type of range that results from doing the liftOver and may have many ALIGNMENT_REQUIRED regions.

A workaround for this effect is to preprocess your confident regions BED file to consist of smaller regions, as that may cause some of the sub-regions to be transformable and others not to be. E.g. if your confident region is chr1  1000   5001000 in the query genome, and the mapping to the target genome maps to chr1 2000 5002001, there is a single basepair insertion in the target genome assembly and consequently GenomeWarp will omit the entire region and any variants within it. If that insertion happened in the last 10 basepairs of the region, then by splitting the confident input region into two:

chr1  1000 5000990   -- maps over to --> chr1 2000 5001990     (equal sized, can be evaluated)
chr1  5000990   5001000   -- maps over to --> chr1 5001990   5002001    (different size, omitted)

a large fraction of the input data would be retained.

An open area for improvement in the code would be to either support reference genome indels or do adaptive splitting of the confident regions to ensure smaller regions do not span variants on the query genome and cause the largest possible regions to be mapped to identically-sized areas.

**Comment by justwalking2017** [comment] 2018-01-05 19:38
Hi, @cmclean 
Appreciate your timely and kind reply.
I followed your suggestion to slice the confident regions of BED files to smaller ones, eg 10k. 1k, 100bp, 10bp. 
By testing on chr1, the retained SNV increase even after 10bp slice.
And the scripts does not work for 2bp slice.
I wonder what's your suggestion for the size of smaller region?
I want to get SNVs as much as I can for my further comparison.
Here are SNVs I got by bed slice on chr1 data:
w10 | 360200
w100 | 358815
w1000 | 354567
w10000 | 345200
w100000 | 294891
no window | 151977
Thanks again!

**Comment by cmclean** [comment] 2018-01-08 15:12
Memory usage and computation cost both increase as you move to smaller window sizes. There is also a higher probability that deletions will be "broken" by the windows, which if you are only interested in SNVs may not be a concern to you. Since your 10 bp window scheme seems empirically best, I'd just go with that if you'd like to use fixed windows. You may be able to improve further by calculating the regions of the query reference genome that are affected by your variant file and ensuring windows boundaries are not occurring in those regions.

**Comment by justwalking2017** [comment] 2018-01-08 15:36
Hi @cmclean ,
Appreciate.
I got confused by another result.
For the  BED1 file referred in the first query, as I mentioned,  2102101 variants transferred when I use VCF1 as query vcf.
When I use SNV-only from VCF1 (a subset of VCF1, in which indels removed) as query vcf, 2896782 variants transferred, which is quiet higher than the VCF1 result.
It means for the same bed file, SNV-only input can get better result that total VCF file.
What's your comments for this kind of result?
Do you have any outline or summary file for your basic considerations in the transfer in genomewarp?

Regards,

**Comment by cmclean** [comment] 2018-01-10 19:19
Hi,

Yes, another type of currently-unsupported transformation is when one or more insertion/deletion variants occur in a region that has mismatching bases or aligns to opposite strands on the target genome: https://github.com/verilylifesciences/genomewarp/blob/master/src/main/java/com/verily/genomewarp/TransformVariantsInRange.java#L134-L138 The reason for this is somewhat complex, but essentially to ensure that the output variants accurately reflect the haplotypes of the individual on the new genome assembly, in this case a full realignment of the haplotypes within the region may be required.

For highest sensitivity in conversion I would do the following, beginning with variants.vcf and confidentRegions.bed:
1. Create a BED file that pads each query variant by 5 bp on either end.
2. Merge intervals in that BED file into non-overlapping intervals, call this variantRegions.bed.
3. Create a BED file containing the other confident regions, i.e. the basewise difference between confidentRegions.bed and variantRegions.bed
4. Segment the basewise-difference BED file into non-overlapping regions of 50 bp, call this nonVariantRegions.bed.
5. Create the final BED file to use as input by concatenating variantRegions.bed and nonVariantRegions.bed. By design, all of these regions should be non-overlapping.

This should probably be implemented within this package, as it's unsatisfying at the moment that you see these differing results and it's not immediately obvious why they should occur. Thanks for bringing it to our attention.

**Comment by deflaux** [comment] 2018-09-19 20:29
Fixed via https://github.com/verilylifesciences/genomewarp/pull/5

**Closed as completed by deflaux** 2018-09-19 20:29 UTC
